return {
	[12187364842] = {
		Name = "Unica One";
		Styles = { "Regular" };
	};

	[12187366475] = {
		Name = "Rubik Maze";
		Styles = { "Regular" };
	};

	[12187364147] = {
		Name = "IBM Plex Sans JP";
		Styles = {
			"Thin",
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold"
		};
	};

	[12187369639] = {
		Name = "Noto Serif JP";
		Styles = { "Extra Light", "Light", "Regular", "Medium", "Semi Bold", "Bold", "Black" };
	};

	[12187361943] = {
		Name = "Parisienne";
		Styles = { "Regular" };
	};

	[12187367666] = {
		Name = "Bungee Shade";
		Styles = { "Regular" };
	};

	[11702779240] = {
		Name = "Raleway";
		Styles = {
			"Thin",
			"Thin Italic",
			"Extra Light",
			"Extra Light Italic",
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[11322590111] = {
		Name = "Fuzzy Bubbles";
		Styles = { "Regular", "Bold" };
	};

	[12187366846] = {
		Name = "Noto Serif HK";
		Styles = {
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Extra Bold",
			"Black"
		};
	};

	[12187363148] = {
		Name = "Rubik Burned";
		Styles = { "Regular" };
	};

	[12187371622] = {
		Name = "Kings";
		Styles = { "Regular" };
	};

	[12187363616] = {
		Name = "Are You Serious";
		Styles = { "Regular" };
	};

	[12187370000] = {
		Name = "Bungee Inline";
		Styles = { "Regular" };
	};

	[12187374537] = {
		Name = "Sono";
		Styles = {
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Extra Bold"
		};
	};

	[12187375422] = {
		Name = "Rajdhani";
		Styles = {
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold"
		};
	};

	[12187365977] = {
		Name = "Rubik";
		Styles = {
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[12187367066] = {
		Name = "Rubik Marker Hatch";
		Styles = { "Regular" };
	};

	[12187607287] = {
		Name = "Prompt";
		Styles = {
			"Thin",
			"Thin Italic",
			"Extra Light",
			"Extra Light Italic",
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[12187377588] = {
		Name = "Tajawal";
		Styles = {
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Bold",
			"Extra Bold",
			"Black"
		};
	};

	[12187361116] = {
		Name = "Hind";
		Styles = {
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold"
		};
	};

	[12187370747] = {
		Name = "Noto Sans";
		Styles = {
			"Thin",
			"Thin Italic",
			"Extra Light",
			"Extra Light Italic",
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[12187372847] = {
		Name = "Barlow";
		Styles = {
			"Thin",
			"Thin Italic",
			"Extra Light",
			"Extra Light Italic",
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[12187368625] = {
		Name = "Roboto Slab";
		Styles = {
			"Thin",
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Extra Bold",
			"Black"
		};
	};

	[12187376545] = {
		Name = "Tangerine";
		Styles = { "Regular", "Bold" };
	};

	[12187376739] = {
		Name = "Noto Serif SC";
		Styles = {
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Black"
		};
	};

	[11702779517] = {
		Name = "Montserrat";
		Styles = {
			"Thin",
			"Thin Italic",
			"Extra Light",
			"Extra Light Italic",
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[12187372629] = {
		Name = "Mulish";
		Styles = {
			"Extra Light",
			"Extra Light Italic",
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[12187607722] = {
		Name = "Damion";
		Styles = { "Regular" };
	};

	[12187377099] = {
		Name = "Cairo";
		Styles = {
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Extra Bold",
			"Black"
		};
	};

	[12187365559] = {
		Name = "Mukta";
		Styles = {
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Extra Bold"
		};
	};

	[12187606783] = {
		Name = "Monofett";
		Styles = { "Regular" };
	};

	[12187371991] = {
		Name = "Barrio";
		Styles = { "Regular" };
	};

	[11598121416] = {
		Name = "Open Sans";
		Styles = {
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic"
		};
	};

	[12187376357] = {
		Name = "Sedgwick Ave Display";
		Styles = { "Regular" };
	};

	[12187375716] = {
		Name = "Finger Paint";
		Styles = { "Regular" };
	};

	[12187372382] = {
		Name = "Eater";
		Styles = { "Regular" };
	};

	[12187373327] = {
		Name = "Work Sans";
		Styles = {
			"Thin",
			"Thin Italic",
			"Extra Light",
			"Extra Light Italic",
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[12187368843] = {
		Name = "Caesar Dressing";
		Styles = { "Regular" };
	};

	[12187373592] = {
		Name = "Kanit";
		Styles = {
			"Thin",
			"Thin Italic",
			"Extra Light",
			"Extra Light Italic",
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[16658254058] = {
		Name = "Arimo";
		Styles = {
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Italic",
			"Medium Italic",
			"Semi Bold Italic",
			"Bold Italic"
		};
	};

	[12187361378] = {
		Name = "Hind Siliguri";
		Styles = {
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold"
		};
	};

	[12187362120] = {
		Name = "Rubik Iso";
		Styles = { "Regular" };
	};

	[8836875837] = {
		Name = "Lobster";
		Styles = { "Regular" };
	};

	[12187374765] = {
		Name = "Playfair Display";
		Styles = {
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[12187374273] = {
		Name = "Italianno";
		Styles = { "Regular" };
	};

	[12187606624] = {
		Name = "PT Serif";
		Styles = {
			"Regular",
			"Italic",
			"Bold",
			"Bold Italic"
		};
	};

	[12187371840] = {
		Name = "Silkscreen";
		Styles = { "Regular", "Bold" };
	};

	[12187607493] = {
		Name = "Shadows Into Light";
		Styles = { "Regular" };
	};

	[12187365104] = {
		Name = "Blaka";
		Styles = { "Regular" };
	};

	[12187377325] = {
		Name = "Nosifer";
		Styles = { "Regular" };
	};

	[12187368093] = {
		Name = "Noto Serif TC";
		Styles = {
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Black"
		};
	};

	[12187373881] = {
		Name = "Yellowtail";
		Styles = { "Regular" };
	};

	[12187367362] = {
		Name = "Pacifico";
		Styles = { "Regular" };
	};

	[12187363887] = {
		Name = "Codystar";
		Styles = { "Light", "Regular" };
	};

	[12187369802] = {
		Name = "Caveat";
		Styles = {
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold"
		};
	};

	[12187364648] = {
		Name = "Marhey";
		Styles = {
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold"
		};
	};

	[12187607116] = {
		Name = "La Belle Aurore";
		Styles = { "Regular" };
	};

	[12187362578] = {
		Name = "Sono Monospace";
		Styles = {
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Extra Bold"
		};
	};

	[16658237174] = {
		Name = "Builder Extended";
		Styles = {
			"Light",
			"Regular",
			"Semi Bold",
			"Bold",
			"Extra Bold"
		};
	};

	[12188570269] = {
		Name = "M PLUS Rounded 1c";
		Styles = {
			"Thin",
			"Light",
			"Regular",
			"Medium",
			"Bold",
			"Extra Bold",
			"Black"
		};
	};

	[12187363368] = {
		Name = "Nunito Sans";
		Styles = {
			"Extra Light",
			"Extra Light Italic",
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[12187374098] = {
		Name = "Monoton";
		Styles = { "Regular" };
	};

	[11598289817] = {
		Name = "Lato";
		Styles = {
			"Thin",
			"Thin Italic",
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Bold",
			"Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[16658246179] = {
		Name = "Builder Mono";
		Styles = { "Light", "Regular", "Bold" };
	};

	[12187376174] = {
		Name = "Teko";
		Styles = {
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold"
		};
	};

	[8764312106] = {
		Name = "Dancing Script";
		Styles = {
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold"
		};
	};

	[12187372175] = {
		Name = "Rye";
		Styles = { "Regular" };
	};

	[12187360881] = {
		Name = "Audiowide";
		Styles = { "Regular" };
	};

	[12187367901] = {
		Name = "Nothing You Could Do";
		Styles = { "Regular" };
	};

	[12187376910] = {
		Name = "Irish Grover";
		Styles = { "Regular" };
	};

	[12187368317] = {
		Name = "Akronim";
		Styles = { "Regular" };
	};

	[12187374954] = {
		Name = "Fira Sans";
		Styles = {
			"Thin",
			"Thin Italic",
			"Extra Light",
			"Extra Light Italic",
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[12187370928] = {
		Name = "Faster One";
		Styles = { "Regular" };
	};

	[12187361718] = {
		Name = "Nanum Gothic";
		Styles = { "Regular", "Bold", "Extra Bold" };
	};

	[12187369046] = {
		Name = "Rubik Wet Paint";
		Styles = { "Regular" };
	};

	[11702779409] = {
		Name = "Poppins";
		Styles = {
			"Thin",
			"Thin Italic",
			"Extra Light",
			"Extra Light Italic",
			"Light",
			"Light Italic",
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic",
			"Extra Bold",
			"Extra Bold Italic",
			"Black",
			"Black Italic"
		};
	};

	[12187366657] = {
		Name = "Lora";
		Styles = {
			"Regular",
			"Italic",
			"Medium",
			"Medium Italic",
			"Semi Bold",
			"Semi Bold Italic",
			"Bold",
			"Bold Italic"
		};
	};

	[12187365769] = {
		Name = "Libre Baskerville";
		Styles = { "Regular", "Italic", "Bold" };
	};

	[12187606934] = {
		Name = "PT Sans";
		Styles = {
			"Regular",
			"Italic",
			"Bold",
			"Bold Italic"
		};
	};

	[16658221428] = {
		Name = "Builder Sans";
		Styles = {
			"Thin",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Extra Bold"
		};
	};

	[12187362892] = {
		Name = "Noto Sans HK";
		Styles = {
			"Thin",
			"Light",
			"Regular",
			"Medium",
			"Bold",
			"Black"
		};
	};

	[12187365364] = {
		Name = "Inter";
		Styles = {
			"Thin",
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Extra Bold",
			"Black"
		};
	};

	[12187371324] = {
		Name = "Quicksand";
		Styles = { "Light", "Regular", "Medium", "Semi Bold", "Bold" };
	};

	[12187375194] = {
		Name = "Frijole";
		Styles = { "Regular" };
	};

	[12187375958] = {
		Name = "Great Vibes";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/AccanthisADFStd.json"] = {
		Name = "Accanthis ADF Std";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/AmaticSC.json"] = {
		Name = "Amatic SC";
		Styles = { "Regular", "Bold" };
	};

	["rbxasset://fonts/families/Arial.json"] = {
		Name = "Arial";
		Styles = { "Regular", "Bold" };
	};

	["rbxasset://fonts/families/LegacyArial.json"] = {
		Name = "Arial (Legacy)";
		Styles = { "Regular", "Bold" };
	};

	["rbxasset://fonts/families/Balthazar.json"] = {
		Name = "Balthazar";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/Bangers.json"] = {
		Name = "Bangers";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/ComicNeueAngular.json"] = {
		Name = "Comic Neue Angular";
		Styles = { "Bold" };
	};

	["rbxasset://fonts/families/Creepster.json"] = {
		Name = "Creepster";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/DenkOne.json"] = {
		Name = "Denk One";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/Fondamento.json"] = {
		Name = "Fondamento";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/FredokaOne.json"] = {
		Name = "Fredoka One";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/GothamSSm.json"] = {
		Name = "Gotham SSm";
		Styles = {
			"Regular",
			"Medium",
			"Bold",
			"Black"
		};
	};

	["rbxasset://fonts/families/GrenzeGotisch.json"] = {
		Name = "Grenze Gotisch";
		Styles = {
			"Thin",
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Extra Bold",
			"Black"
		};
	};

	["rbxasset://fonts/families/Guru.json"] = {
		Name = "Guru";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/HighwayGothic.json"] = {
		Name = "Highway Gothic";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/Inconsolata.json"] = {
		Name = "Inconsolata";
		Styles = {
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Extra Bold",
			"Black"
		};
	};

	["rbxasset://fonts/families/IndieFlower.json"] = {
		Name = "Indie Flower";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/JosefinSans.json"] = {
		Name = "Josefin Sans";
		Styles = {
			"Thin",
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold"
		};
	};

	["rbxasset://fonts/families/Jura.json"] = {
		Name = "Jura";
		Styles = {
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold"
		};
	};

	["rbxasset://fonts/families/Kalam.json"] = {
		Name = "Kalam";
		Styles = {
			"Light",
			"Regular",
			"Bold"
		};
	};

	["rbxasset://fonts/families/LuckiestGuy.json"] = {
		Name = "Luckiest Guy";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/Merriweather.json"] = {
		Name = "Merriweather";
		Styles = {
			"Light",
			"Regular",
			"Bold",
			"Black"
		};
	};

	["rbxasset://fonts/families/Michroma.json"] = {
		Name = "Michroma";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/Oswald.json"] = {
		Name = "Oswald";
		Styles = {
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold"
		};
	};

	["rbxasset://fonts/families/PatrickHand.json"] = {
		Name = "Patrick Hand";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/PermanentMarker.json"] = {
		Name = "Permanent Marker";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/PressStart2P.json"] = {
		Name = "Press Start 2P";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/Roboto.json"] = {
		Name = "Roboto";
		Styles = {
			"Thin",
			"Light",
			"Regular",
			"Medium",
			"Bold",
			"Black"
		};
	};

	["rbxasset://fonts/families/RobotoCondensed.json"] = {
		Name = "Roboto Condensed";
		Styles = { "Light", "Regular", "Bold" };
	};

	["rbxasset://fonts/families/RobotoMono.json"] = {
		Name = "Roboto Mono";
		Styles = {
			"Thin",
			"Extra Light",
			"Light",
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold"
		};
	};

	["rbxasset://fonts/families/RomanAntique.json"] = {
		Name = "Roman Antique";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/Sarpanch.json"] = {
		Name = "Sarpanch";
		Styles = {
			"Regular",
			"Medium",
			"Semi Bold",
			"Bold",
			"Extra Bold",
			"Black"
		};
	};

	["rbxasset://fonts/families/SourceSansPro.json"] = {
		Name = "Source Sans Pro";
		Styles = {
			"Extra Light",
			"Light",
			"Regular",
			"Semi Bold",
			"Bold",
			"Black"
		};
	};

	["rbxasset://fonts/families/SpecialElite.json"] = {
		Name = "Special Elite";
		Styles = { "Regular" };
	};

	["rbxasset://fonts/families/TitilliumWeb.json"] = {
		Name = "Titillium Web";
		Styles = {
			"Extra Light",
			"Light",
			"Regular",
			"Semi Bold",
			"Bold",
			"Black"
		};
	};

	["rbxasset://fonts/families/Ubuntu.json"] = {
		Name = "Ubuntu";
		Styles = {
			"Light",
			"Regular",
			"Medium",
			"Bold"
		};
	};

	["rbxasset://fonts/families/Zekton.json"] = {
		Name = "Zekton";
		Styles = { "Regular" };
	};

	--[[
	[0] = {
		Name = "";
		Styles = {};
	};
	--]]
}